version: 2.1
jobs:
  I-Have-Code:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: what-branch
          command: |
            GIT_SHA=$(git rev-parse --short HEAD)
            GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            GIT_LOG_MSG=$(git log --format='%s' -1 | head -1 | perl -pe 's/%/%%/')
            printf "* $GIT_BRANCH -> $GIT_SHA -> ${GIT_LOG_MSG}\n"
            ls -lart
            pwd
            echo @@@
            git checkout master
            ls -lart
            git rev-parse --short HEAD
            git rev-parse --abbrev-ref HEAD
            git log --format='%s' -1 | head -1 | perl -pe 's/%/%%/'
            
  Run-With-Node:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Running In A Container With Node
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - I-Have-Code:
         filters:
           branches:
             ignore: /^this/
           tags:
             ignore: /.*/
     - Run-With-Node
     - Hold-For-Approval:
         type: approval
         requires:
           - Run-With-Node
           - I-Have-Code
     - Now-Complete:
         requires:
           - Hold-For-Approval
