version: 2.1

jobs:
  foop:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: what-branch
          command: |
            ./scripts/install-branch.sh

  foop2:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: what-branch
          command: |
            ./scripts/install-branch.sh
            
workflows:
 version: 2
 foop:
   jobs:
     - foop:
         filters:
           branches:
             ignore: /^this*/
           tags:
             ignore: /.*/
     - foop2:
         filters:
           branches:
             ignore: /^this*/
           tags:
             ignore: /.*/
         requires:
           - foop