version: 2.1
jobs:
  foop:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: run the tests if the sha has changed
          command: ./scripts/maybe-run-tests.sh
            

workflows:
 version: 2
 foop:
   jobs:
     - foop:
         filters:
           branches:
             ignore: /^that.*/
           tags:
             ignore: /.*/
