version: 2.1
jobs:
  I-Have-Code:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: what-branch
          command: ../scripts/install-branch.sh
            
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - I-Have-Code:
         filters:
           branches:
             ignore: /^this/
           tags:
             ignore: /.*/
