version: 2.1
#
jobs:
  foop:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-previous-fxa-content-version-commit-sha
      - run:
          name: check current __version__ commit sha
          command: |
            PREVIOUS_SHA=""
            if [ -f ./previous-fxa-content-version-commit-sha.txt ]; then
              PREVIOUS_SHA="${cat ./previous-fxa-content-version-commit-sha.txt)"
            fi
            /bin/echo PREVIOUS_SHA: $PREVIOUS_SHA
            COMMIT_SHA=$(curl -s https://accounts.stage.mozaws.net/__version__ | perl -ne 'next unless /"commit":\s+"([^"]*)"/; print $1, $/')
            /bin/echo COMMIT_SHA: $COMMIT_SHA
            /bin/echo -n $COMMIT_SHA > previous-fxa-content-version-commit-sha.txt
      - save_cache:
          keys: v1-previous-fxa-content-version-commit-sha
          paths: 
            - previous-fxa-content-version-commit-sha.txt

  foop2:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: what-branch
          command: |
            ./scripts/install-branch.sh
            
workflows:
 version: 2
 foop:
   jobs:
     - foop:
         filters:
           branches:
             ignore: /^this*/
           tags:
             ignore: /.*/
     - foop2:
         filters:
           branches:
             ignore: /^this*/
           tags:
             ignore: /.*/
         requires:
           - foop