version: 2.1
#
jobs:
  foop:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - previous-fxa-content-version-commit-sha
      - run:
          name: what-branch
          command: |
            ./scripts/install-branch.sh
      - run:
          name: check current __version__ commit sha
          command: |
            COMMIT_SHA=$(curl -s https://accounts.stage.mozaws.net/__version__ | perl -ne 'next unless /"commit":\s+"([^"]*)"/; print $1, $/')
            echo COMMIT_SHA: $COMMIT_SHA

  foop2:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: what-branch
          command: |
            ./scripts/install-branch.sh
            
workflows:
 version: 2
 foop:
   jobs:
     - foop:
         filters:
           branches:
             ignore: /^this*/
           tags:
             ignore: /.*/
     - foop2:
         filters:
           branches:
             ignore: /^this*/
           tags:
             ignore: /.*/
         requires:
           - foop