version: 2.1
jobs:
  I-Have-Code:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: what-branch
          command: |
            ls -lart
            git rev-parse --short HEAD
            git rev-parse --abbrev-ref HEAD
            git log --format='%s' -1 | head -1 | perl -pe 's/%/%%/'
            pwd
            echo @@@
            git checkout master
            ls -lart
            git rev-parse --short HEAD
            git rev-parse --abbrev-ref HEAD
            git log --format='%s' -1 | head -1 | perl -pe 's/%/%%/'
            
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - I-Have-Code:
         filters:
           branches:
             ignore: /^this/
           tags:
             ignore: /.*/
