version: 2.1
jobs:
  foop:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: what-branch
          command: |
            ls -lart --full-time
            ./scripts/install-branch.sh
            
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - foop:
         filters:
           branches:
             ignore: /^this*/
           tags:
             ignore: /.*/
